---
# This workflow will run unit tests and deploy the application to a
# target environment

name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "**.md" # All markdown files in the repository

jobs:

  deploy:
    if: github.repository_owner == '18F'
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Set flow config
        run: |
          echo "$FLOW_CONFIG_${{ steps.cf-setup.outputs.target-environment-upper }}" vars-env.yaml

      - name: Deploy application
        run: cf push --vars-file vars.yaml --vars-file vars-env.yaml
          --var ENVIRONMENT=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling
